
  app:
    name: "项目名"
    mode: "模式"
    port: 端口
    version: "版本"
    start_time: "创建时间"
    machine_id: 1
    #数据库
  mysql:
    host: "服务器地址"
    port: "端口"
    user: "用户名"
    password: "密码"
    dbname: "数据库"
    max_open_conns: 200
    max_idle_conns: 50
  redis:
    db: redis仓库
    addr: IP:端口
    password: "密码"
  log:
    level: "日志水平"
    filename: "日志名称"
    max_size: 200
    max_age: 30
    max_backups: 7
  auth:
    jwt_expire: 
  kafka:
    address: "IP:端口"



